name: equatable_expect
description: This is a simple package which helps you debug while writing tests. It pinpoints what is wrong with your data when comparing Equatable objects
version: 0.1.1
homepage: https://github.com/ton-An/equatable_expect

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter: